In [1]:
%pip install pandas requests python-dotenv matplotlib

Requirement already satisfied: pandas in /Users/matthewlim/PycharmProjects/CYPLAN101_Project_G16/venv/lib/python3.13/site-packages (3.1.0)
Requirement already satisfied: requests in /Users/matthewlim/PycharmProjects/CYPLAN101_Project_G16/venv/lib/python3.13/site-packages (2.34.2)
Requirement already satisfied: python-dotenv in /Users/matthewlim/PycharmProjects/CYPLAN101_Project_G16/venv/lib/python3.13/site-packages (1.2.4)
Collecting matplotlib
  Downloading matplotlib-3.11.2-cp313-cp313-macosx_11_0_arm64.whl.metadata (80 kB)
Requirement already satisfied: numpy>=2.0.2 in /Users/matthewlim/PycharmProjects/CYPLAN101_Project_G16/venv/lib/python3.13/site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.9.0 in /Users/matthewlim/PycharmProjects/CYPLAN101_Project_G16/venv/lib/python3.13/site-packages (from pandas) (3.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/matthewlim/PycharmProjects/CYPLAN101_Project_G16/venv/lib/python3.13/site-packages (from requests) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/matthewlim/PycharmProjects/CYPLAN101_Project_G16/venv/lib/python3.13/site-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/matthewlim/PycharmProjects/CYPLAN101_Project_G16/venv/lib/python3.13/site-packages (from requests) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in /Users/matthewlim/PycharmProjects/CYPLAN101_Project_G16/venv/lib/python3.13/site-packages (from requests) (2026.10.23)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.4.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Downloading fonttools-4.68.0-cp313-cp313-macosx_10_13_universal2.whl.metadata (139 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in /Users/matthewlim/PycharmProjects/CYPLAN101_Project_G16/venv/lib/python3.13/site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-13.0.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.1 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: six>=1.6 in /Users/matthewlim/PycharmProjects/CYPLAN101_Project_G16/venv/lib/python3.13/site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Requirement already satisfied: tzdata in /Users/matthewlim/PycharmProjects/CYPLAN101_Project_G16/venv/lib/python3.13/site-packages (from python-dateutil>=2.9.0->pandas) (2026.5)
Downloading matplotlib-3.11.2-cp313-cp313-macosx_11_0_arm64.whl (9.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 33.0 MB/s  0:00:00 eta 0:00:01
Downloading contourpy-1.4.0-cp313-cp313-macosx_11_0_arm64.whl (285 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.68.0-cp313-cp313-macosx_10_13_universal2.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 19.7 MB/s  0:00:00
Downloading kiwisolver-1.5.1-cp313-cp313-macosx_11_0_arm64.whl (64 kB)
Downloading pillow-13.0.0-cp313-cp313-macosx_11_0_arm64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 32.7 MB/s  0:00:00
Downloading pyparsing-3.3.3-py3-none-any.whl (126 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [matplotlib]7 [matplotlib]
Successfully installed contourpy-1.4.0 cycler-0.12.1 fonttools-4.68.0 kiwisolver-1.5.1 matplotlib-3.11.2 pillow-13.0.0 pyparsing-3.3.3

[notice] A new release of pip is available: 26.0.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv(usecwd=True))

CENSUS_API_KEY = os.getenv("CENSUS_API_KEY")

if not CENSUS_API_KEY:
    raise ValueError("CENSUS_API_KEY is missing from .env")

Matplotlib is building the font cache; this may take a moment.

In [3]:
url = "https://api.census.gov/data/2024/acs/acs5"

params = {
    "get": (
        "NAME,"
        "B19013_001E,"
        "B08201_001E,"
        "B08201_002E,"
        "B08301_001E,"
        "B08301_010E"
    ),
    "for": "tract:*",
    "in": "state:06 county:075",
    "key": CENSUS_API_KEY
}

response = requests.get(url, params=params, timeout=60)
response.raise_for_status()

data = response.json()

acs = pd.DataFrame(data[1:], columns=data[0])

acs.head(10)

,NAME,B19013_001E,B08201_001E,B08201_002E,B08301_001E,B08301_010E,state,county,tract
0,Census Tract 101.01; San Francisco County; Cal...,89022,1216,451,1167,216,06,075,010101
1,Census Tract 101.02; San Francisco County; Cal...,102826,930,347,931,133,06,075,010102
2,Census Tract 102.01; San Francisco County; Cal...,156017,1399,454,1812,268,06,075,010201
3,Census Tract 102.02; San Francisco County; Cal...,176958,1099,150,1284,119,06,075,010202
4,Census Tract 103; San Francisco County; Califo...,158144,2060,455,2655,188,06,075,010300
5,Census Tract 104.01; San Francisco County; Cal...,181705,953,355,1299,108,06,075,010401
6,Census Tract 104.02; San Francisco County; Cal...,203354,1233,329,1280,68,06,075,010402
7,Census Tract 105; San Francisco County; Califo...,179896,1848,636,1869,300,06,075,010500
8,Census Tract 106; San Francisco County; Califo...,75938,1723,1217,1779,616,06,075,010600
9,Census Tract 107.01; San Francisco County; Cal...,24854,1792,1531,957,447,06,075,010701

In [4]:
# RENAME COLS
acs = acs.rename(columns={
    "NAME": "tract_name",
    "B19013_001E": "median_household_income",
    "B08201_001E": "total_households",
    "B08201_002E": "households_without_vehicle",
    "B08301_001E": "total_workers",
    "B08301_010E": "public_transit_commuters"
})

In [10]:
acs.head(10)

,tract_name,median_household_income,total_households,households_without_vehicle,total_workers,public_transit_commuters,state,county,tract
0,Census Tract 101.01; San Francisco County; Cal...,89022,1216,451,1167,216,06,075,010101
1,Census Tract 101.02; San Francisco County; Cal...,102826,930,347,931,133,06,075,010102
2,Census Tract 102.01; San Francisco County; Cal...,156017,1399,454,1812,268,06,075,010201
3,Census Tract 102.02; San Francisco County; Cal...,176958,1099,150,1284,119,06,075,010202
4,Census Tract 103; San Francisco County; Califo...,158144,2060,455,2655,188,06,075,010300
5,Census Tract 104.01; San Francisco County; Cal...,181705,953,355,1299,108,06,075,010401
6,Census Tract 104.02; San Francisco County; Cal...,203354,1233,329,1280,68,06,075,010402
7,Census Tract 105; San Francisco County; Califo...,179896,1848,636,1869,300,06,075,010500
8,Census Tract 106; San Francisco County; Califo...,75938,1723,1217,1779,616,06,075,010600
9,Census Tract 107.01; San Francisco County; Cal...,24854,1792,1531,957,447,06,075,010701

In [12]:
# CONVERT TO PROPER DTYPES and CREATE PERCENTAGE COLS
numeric_cols = [
    "median_household_income",
    "total_households",
    "households_without_vehicle",
    "total_workers",
    "public_transit_commuters"
]

acs[numeric_cols] = acs[numeric_cols].apply(
    pd.to_numeric, errors="coerce"
)

In [13]:
acs["pct_without_vehicle"] = (
    acs["households_without_vehicle"]
    / acs["total_households"].replace(0, np.nan) * 100
)

acs["pct_transit_commuters"] = (
    acs["public_transit_commuters"]
    / acs["total_workers"].replace(0, np.nan) * 100
)

In [14]:
acs.head(10)

,tract_name,median_household_income,total_households,households_without_vehicle,total_workers,public_transit_commuters,state,county,tract,pct_without_vehicle,pct_transit_commuters
0,Census Tract 101.01; San Francisco County; Cal...,89022,1216,451,1167,216,06,075,010101,37.088816,18.508997
1,Census Tract 101.02; San Francisco County; Cal...,102826,930,347,931,133,06,075,010102,37.311828,14.285714
2,Census Tract 102.01; San Francisco County; Cal...,156017,1399,454,1812,268,06,075,010201,32.451751,14.790287
3,Census Tract 102.02; San Francisco County; Cal...,176958,1099,150,1284,119,06,075,010202,13.648772,9.267913
4,Census Tract 103; San Francisco County; Califo...,158144,2060,455,2655,188,06,075,010300,22.087379,7.080979
5,Census Tract 104.01; San Francisco County; Cal...,181705,953,355,1299,108,06,075,010401,37.250787,8.314088
6,Census Tract 104.02; San Francisco County; Cal...,203354,1233,329,1280,68,06,075,010402,26.682887,5.312500
7,Census Tract 105; San Francisco County; Califo...,179896,1848,636,1869,300,06,075,010500,34.415584,16.051364
8,Census Tract 106; San Francisco County; Califo...,75938,1723,1217,1779,616,06,075,010600,70.632618,34.626194
9,Census Tract 107.01; San Francisco County; Cal...,24854,1792,1531,957,447,06,075,010701,85.435268,46.708464

In [16]:
acs.shape

(244, 11)